spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: post123
    url: jdbc:postgresql://172.19.0.3:30000/insulina-control-db